# Site settings
author: Amit Singh
title: How I got here
header-img: img/home-bg.png
email: amit_nyc@live.com
copyright_name: Amit Singh
description: > # this means to ignore newlines until "baseurl:"
  My coding journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amitnyc83

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
