# Site settings
title: How I got here
header-img: img/home-bg.png
email: amit_nyc@live.com
copyright_name: amitnyc83
description: > # this means to ignore newlines until "baseurl:"
  My coding journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  amitnyc83
learn_profile: amitnyc83
email_username: amit_nyc@live.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
